### ISSUE TITLE
Access as a service

### ISSUE THREAD

**Issue by NVentimiglia** [imperugo/Microsoft.Extensions.Logging.Slack#1]
Is there a way to access this logger directly? (As a service). Would like to customize my messages a little more and log multiple trace levels (non-errors) without having to worry about system and framework spam.

**Comment by imperugo** [comment]
Hi @NVentimiglia 
of course you can. You have to initialize this class

https://github.com/imperugo/Microsoft.Extensions.Logging.Slack/blob/master/Microsoft.Extensions.Logging.Slack/SlackLogger.cs

Manually or via DI (register first)

**Comment by NVentimiglia** [comment]
Perfect, good stuff.
